### ISSUE TITLE
Company relocations - feedback

### ISSUE THREAD

**Issue by skenaja** [dchaplinsky/german_registry_parser#11]
https://github.com/dchaplinsky/german_registry_parser/blob/ed82c9059a4777dea2d78f0d29360ad6a91cdd29/parsing_results/sample2/354650.json#L41-L45

Good first pass!

1) Can you also extract out the court name from `Amtsgericht Bremen`? eg to `related_amtsgericht: "Bremen"`
2) company number label should just be `company_number` rather than `hrb` as there are different forms of number (with HRA, HRB, GnR, VR, PR prefixes)
3) some company numbers have suffixes, like the one in this notice ("BHV") => `"company_number": "HRB 1864 BHV"`
4) can you include whether the company number/court is the former one or the replacement, in this example, it's the previous registration so use `"registration": "predecessor"`. For the other case, use `"registration": "successor"`.

**Comment by dchaplinsky** [comment]
Ok, gonna try it today.

Can you remind me how can I identify pred/succ registration?

**Comment by skenaja** [comment]
Refer back to email of Wed, 20 Jun 2018 17:08:19 "Re: German registry parser" - I can forward again if required

**Comment by dchaplinsky** [comment]
I've added support for HRA, HRB, GnR, VR, PR (however found no examples of anything but HRA/HRB in my samples).

I've added also suffixes.

Courts city are now parsed as well.

Everything found using "Sitzverlegung" marker is now has `"registration": "predecessor"`, but I think sometime it's wrong.

I'm gonna to cover more cases tomorrow.
Please review results and let me know
