### ISSUE TITLE
Missing officer

### ISSUE THREAD

**Issue by skenaja** [dchaplinsky/german_registry_parser#13]
https://github.com/dchaplinsky/german_registry_parser/blob/76cff22e96849aa861974dd59f0f41683ab48d98/parsing_results/sample1/95335.json#L8

`Rippegather, Dietmar, Mönchengladbach, *23.03.1957.`

**Comment by skenaja** [comment]
Parser misses an officer from this notice: https://www.handelsregisterbekanntmachungen.de/skripte/hrb.php?rb_id=178404&land_abk=by

`Schaaf, Christian Wilhelm, Egling, *23.04.1966`

**Comment by skenaja** [comment]
Missed officer from this notice:
https://www.handelsregisterbekanntmachungen.de/skripte/hrb.php?rb_id=1625989&land_abk=nw

` Gronemeier, Manfred, Bielefeld, *17.12.1948`

**Comment by skenaja** [comment]
https://www.handelsregisterbekanntmachungen.de/en/skripte/hrb.php?rb_id=907832&land_abk=nw

Missing officers (Only the first one has been parsed):

`Geschäftsführer: Eckerle, Philipp, Aachen, *13.04.1980; Golubowitsch, Alexander, Erftstadt, *16.09.1976; Dr. Kessell, Andreas, Aachen, *29.12.1976`

**Comment by dchaplinsky** [comment]
Please stop reporting it for a while :)

I'm about to push the fix.

**Comment by skenaja** [comment]
lol - will leave you to it!

**Comment by dchaplinsky** [comment]
Okay, feel free to test. Some false positives should disappear as well.

I'd appreciate a proper QA, as this change is introducing new heuristic and
has big impact.

**Comment by skenaja** [comment]
I carried out a lot of QA against sample2 on this one - Many of the missing officers are now present.

There were a few findings relating to officers from the QA which I'll raise in a new ticket.
