### ISSUE TITLE
"Vendor" requirements.txt

### ISSUE THREAD

**Issue by skenaja** [dchaplinsky/german_registry_parser#15]
Hi @dchaplinsky - I've been asked if you are able to "vendor" the requirements.txt, i.e. have them installed inside the python application, so we don't have to worry about installing the dependencies ourselves & so that we can run the code direct

**Comment by dchaplinsky** [comment]
I doubt it, because of NLTK (which I think is partially written in C). But I'll try.

What is your target python version?

**Comment by dchaplinsky** [comment]
Okay, I've been wrong.
Here you go: https://github.com/dchaplinsky/german_registry_parser/tree/vendor

**Comment by skenaja** [comment]
I can confirm this works correctly. Can you merge to `master`?

**Comment by skenaja** [comment]
Resolved via https://github.com/dchaplinsky/german_registry_parser/pull/17
