### ISSUE TITLE
Update flag - ignore_for_now

### ISSUE THREAD

**Issue by skenaja** [dchaplinsky/german_registry_parser#7]
{
                "flag": "ignore_for_now",
                "text": "Die\\ Gesellschaft\\ ist\\ aufgelöst\\."
            }

* Please could you set this flag to "CompanyClosed"
* example gazette notice: https://www.handelsregisterbekanntmachungen.de/en/skripte/hrb.php?rb_id=803201&land_abk=by

**Comment by dchaplinsky** [comment]
Done.

How does it look so far? Usable? What is the area you want me to work on the most right now?

**Comment by skenaja** [comment]
Pretty usable so far. Can you look at related_registrations?

**Comment by dchaplinsky** [comment]
On it tomorrow
